from . import product
from . import membership_request
from . import membership
from . import res_partner
from . import res_users
from . import structure
from . import address_local_zip
from . import wizard
from . import virtual_models
from . import report
from . import sub_abstract_coordinate
from . import email_coordinate
from . import address_address
from . import phone_phone
from . import partner_relation
from . import mandate
from . import models
