# Copyright 2018 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    'name': 'Mozaik: Membership',
    'summary': """
        Manage memberships""",
    'version': '11.0.1.0.0',
    'license': 'AGPL-3',
    'author': 'ACSONE SA/NV',
    'website': 'https://acsone.eu/',
    'category': 'Political Association',
    'depends': [
        'product',
        'mozaik_person',
        'mozaik_person_coordinate',
        'mozaik_structure',
        'mozaik_mandate',
    ],
    'data': [
        'data/membership_state.xml',
        'data/ir_config_parameter.xml',
        'data/product.xml',
        'data/ir_cron.xml',
        'security/membership_security.xml',
        'security/ir.model.access.csv',
        'membership_workflow.xml',
        'views/product.xml',
        'views/membership_state.xml',
        'views/membership_line.xml',
        'views/address_local_zip.xml',
        'views/coordinate.xml',
        'views/partner_involvement.xml',
        'views/partner_relation.xml',
        'views/mandate.xml',
        'views/int_instance.xml',
        'views/res_partner.xml',
        'views/membership_menu.xml',
        'wizards/change_main_address.xml',
        'wizards/force_int_instance.xml',
        'wizards/generate_reference.xml',
        'wizards/pass_former_member.xml',
    ],
    'demo': [
    ],
    'installable': False,
}
