# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Mozaik Association
org_slug: mozaik-association
rebel_module_groups: []
repo_description: '...'
repo_name: Mozaik
repo_slug: mozaik
repo_website: https://github.com/mozaik-association/mozaik
travis_apt_packages: []
travis_apt_sources: []

