# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.0-69-gb5e26ae
_src_path: git+https://github.com/acsone/oca-addons-repo-template
dependency_installation_mode: PIP
generate_requirements_txt: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: '...'
repo_name: Mozaik
repo_slug: mozaik
travis_apt_packages: []
travis_apt_sources: []
