language: python
sudo: false
cache: pip

python:
  - "2.7.13"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="l10n_mozaik,mozaik_sample_accounting,mozaik_sample_customization"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="l10n_mozaik,mozaik_sample_accounting,mozaik_sample_customization"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install anybox.testing.openerp phonenumbers unicodecsv
  - travis_install_nightly

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/odoo_addons
  - travis_run_tests

after_success:
  - travis_after_tests_success
