language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="mozaik_sample_customization"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="mozaik_sample_customization"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/odoo/addons
  - pip install phonenumbers
  - travis_run_tests

after_success:
  travis_after_tests_success
