site_name: Mozaik Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tags.sticky

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



