site_name: Mozaik Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tags.sticky

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - abbr
  - attr_list
  - pymdownx.snippets


  - attr_list
  - md_in_html
  - pymdownx.superfences

  - admonition
  - pymdownx.details
  - pymdownx.superfences


  - attr_list
  - md_in_html
